# -*- coding: utf-8 -*-
"""Mohammad Mahin - In Class Activity 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR8egQ8qfk-dxsTfaH3GKyDYWGXXHKM3

Question #1
"""

import turtle

# Set up the turtle
t = turtle.Turtle()
t.speed(1)  # Set the speed of drawing

# Draw an octagon using a for loop
for _ in range(8):
    t.forward(100)  # Move forward by 100 units
    t.right(45)     # Turn right by 45 degrees

# Complete the drawing
turtle.done()

import turtle

# Set up the turtle
t = turtle.Turtle()
t.speed(1)  # Set the speed of drawing

# Draw an octagon without using a for loop
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)
t.right(45)
t.forward(100)

# Complete the drawing
turtle.done()

"""Question #2"""

import turtle

# Create the first turtle
star_turtle = turtle.Turtle()
star_turtle.color("blue")  # Set color for the first turtle

# Draw the first five-pointed star using a for loop
for _ in range(5):
    star_turtle.forward(100)   # Move forward
    star_turtle.right(144)      # Turn right by 144 degrees

# Create the second turtle and move it to a new location
second_star_turtle = turtle.Turtle()
second_star_turtle.color("red")  # Set color for the second turtle
second_star_turtle.penup()        # Lift pen to move without drawing
second_star_turtle.goto(-150, -150)  # Move to a new location
second_star_turtledown()          # Put pen down to start drawing

# Draw the second five-pointed star at the new location using a for loop
for _ in range(5):
    second_star_turtle.forward(100)
    second_star_turtleright(144)

turtle.done()  # Finish drawing and keep window open

import turtle

# Create the first turtle
star_turtle = turtle.Turtle()
star_turtle.color("blue")  # Set color for the first turtle

# Draw the first five-pointed star
star_turtle.forward(100)  # Move forward
star_turtle.right(144)     # Turn right by 144 degrees
star_turtle.forward(100)   # Move forward
star_turtle.right(144)     # Turn right by 144 degrees
star_turtle.forward(100)   # Move forward
star_turtle.right(144)     # Turn right by 144 degrees
star_turtle.forward(100)   # Move forward
star_turtle.right(144)     # Turn right by 144 degrees
star_turtle.forward(100)   # Move forward

# Create the second turtle and move it to a new location
second_star_turtle = turtle.Turtle()
second_star_turtle.color("red")  # Set color for the second turtle
second_star_turtle.penup()        # Lift pen to move without drawing
second_star_turtle.goto(-150, -150)  # Move to a new location
second_star_turtle.pendown()      # Put pen down to start drawing

# Draw the second five-pointed star at the new location
second_star_turtle.forward(100)
second_star_turtle.right(144)
second_star_turtle.forward(100)
second_star_turtle.right(144)
second_star_turtle.forward(100)
second_star_turtle.right(144)
second_star_turtle.forward(100)
second_star_turtle.right(144)
second_star_turtle.forward(100)

turtle.done()  # Finish drawing and keep window open

"""Question #3"""

import turtle

# Set up the turtle
t = turtle.Turtle()

# Draw a square using a for loop
for _ in range(4):
    t.forward(100)  # Move forward by 100 units
    t.right(90)     # Turn right by 90 degrees

# Complete the drawing
turtle.done()

import turtle

# Set up the turtle
t = turtle.Turtle()

# Draw a square without using a for loop
t.forward(100)  # Move forward by 100 units
t.right(90)     # Turn right by 90 degrees
t.forward(100)  # Move forward by 100 units
t.right(90)     # Turn right by 90 degrees
t.forward(100)  # Move forward by 100 units
t.right(90)     # Turn right by 90 degrees
t.forward(100)  # Move forward by 100 units

# Complete the drawing
turtle.done()

"""Question #4"""

for i in range(1, 4):
    print("*" * i)

print("*")
print("**")
print("***")