# -*- coding: utf-8 -*-
"""Mohammad_Mahin_In_Class_Activity_Lesson 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtszNFKHaezRMPJCi8eHc_eXEvzrbXS0
"""

# Step 1: Assign values to variables
base = 10  # length of the base in cm
height = 4  # height of the triangle in cm

# Step 2: Calculate area
area = (1/2) * base * height

# Step 3: Display result
print("The area of the triangle is:", area, "cm²")

# Step 1: Define variables
garden_length = 50  # in cm
garden_width = 80   # in cm
fence_length = 15   # in cm

# Step 2: Calculate garden perimeter
garden_perimeter = 2 * (garden_length + garden_width)

# Step 3: Calculate number of fences needed
number_of_fences = -(-garden_perimeter // fence_length)  # Using ceiling division

# Step 4: Print final result
print(f"Number of fences needed: {number_of_fences}")

# Step 1: Define total amount in cents
total_cents = 835

# Step 2: Calculate number of dollars
dollars = total_cents // 100

# Step 3: Calculate remaining cents after extracting dollars
remaining_after_dollars = total_cents % 100

# Step 4: Calculate number of dimes
dimes = remaining_after_dollars // 10

# Step 5: Calculate remaining cents after extracting dimes
remaining_after_dimes = remaining_after_dollars % 10

# Step 6: Calculate number of quarters
quarters = remaining_after_dimes // 25

# Output results
print(f"Total Amount: {total_cents} cents")
print(f"Dollars: {dollars}")
print(f"Dimes: {dimes}")
print(f"Quarters: {quarters}")

print("One")
print("\tTwo")
print("\t\tThree")

# Step 1: Ask the user for their name
user_name = input("Please enter your name: ")

# Step 2: Format the output message using escape characters
message = f'"{user_name}" is a common name.'

# Step 3: Print the result
print(message)

# Define the file path using escape characters
file_path = "C:\\Users\\Documents\\MyFile.txt"

# Print the file path
print(file_path)