# -*- coding: utf-8 -*-
"""Mohammad Mahin - In Class Activity Lesson 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnEE_8X3wFuLSPvg2ZUwtx0lKOsqF8rY

Question #1
"""

def display_info():
    # Information about my favorite book
    title = "1984"
    author = "George Orwell"
    description = ("1984 is a dystopian novel set in a totalitarian society ruled by Big Brother. "
                   "It explores themes of surveillance, censorship, and individuality.")

    # Printing the information
    print(f"Title: {title}")
    print(f"Author: {author}")
    print(f"Description: {description}")

# Calling the function to showcase the details
display_info()

"""Question #2"""

def london_attractions():
    attractions = [
        "The British Museum",
        "The Tower of London",
        "Buckingham Palace",
        "The Houses of Parliament and Big Ben",
        "The London Eye",
        "The Tate Modern",
        "St. Paul's Cathedral",
        "Covent Garden"
    ]
    print("Top Attractions in London:")
    for attraction in attractions:
        print(f"- {attraction}")

def paris_attractions():
    attractions = [
        "Eiffel Tower",
        "Louvre Museum",
        "Notre-Dame Cathedral",
        "Montmartre and the Basilica of Sacré-Cœur",
        "Champs-Élysées and Arc de Triomphe",
        "Palace of Versailles",
        "Musée d'Orsay",
        "Seine River Cruises"
    ]
    print("Top Attractions in Paris:")
    for attraction in attractions:
        print(f"- {attraction}")

def new_york_attractions():
    attractions = [
        "Statue of Liberty and Ellis Island",
        "Central Park",
        "Metropolitan Museum of Art (The Met)",
        "Times Square",
        "Broadway and the Theater District",
        "9/11 Memorial and Museum",
        "Brooklyn Bridge",
        "Empire State Building"
    ]
    print("Top Attractions in New York:")
    for attraction in attractions:
        print(f"- {attraction}")

# Example usage
london_attractions()
paris_attractions()
new_york_attractions()

"""Question #3"""

import turtle

def draw_square():
    # Fixed side length for the square
    side_length = 100

    # Draw a square
    for _ in range(4):
        turtle.forward(side_length)  # Move forward by side_length
        turtle.right(90)              # Turn right by 90 degrees

# Set up the turtle environment
turtle.speed(1)  # Set speed of drawing (1 is slowest, 10 is fastest)

# Draw first square
draw_square()

# Move to a new position for second square
turtle.penup()   # Lift pen so it doesn't draw while moving
turtle.goto(150, 0)  # Move to new coordinates (150, 0)
turtle.pendown() # Put pen down to start drawing

# Draw second square
draw_square()

# Move to a new position for third square
turtle.penup()
turtle.goto(-150, 0)  # Move to new coordinates (-150, 0)
turtle.pendown()

# Draw third square
draw_square()

# Finish drawing
turtle.done()

"""Question #4"""

def find_even_numbers():
    even_numbers = []  # Step 2: Initialize an empty list
    for num in range(11):  # Step 3: Loop through numbers from 0 to 10
        if num % 2 == 0:   # Step 4: Check if the number is even
            even_numbers.append(num)  # Step 5: Append to list if it's even
    print(even_numbers)   # Step 6: Print the list of even numbers

# Call the function to see results
find_even_numbers()